### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by npeltier** [npeltier/sling-pipes#5]
a user interface would be nice :-) for now a tree explorer, or vault are needed to create the configuration and make it a bit cumbersome to create / update pipes. 
An interface listing available pipes, allowing to quickly configure them, validating also values, helping the user by showing which resources such & such pipes output configured as this, would make this whole tool much better.

**Comment by dlh3** [comment]
I agree!  A drag-n-drop pipeline builder would be fantastic.  I think this could be similar to the AEM Workflow editor.
![workflows](https://cloud.githubusercontent.com/assets/648035/11574699/025e1eac-99c2-11e5-9eef-3aff74c4ce19.PNG)

**Comment by npeltier** [comment]
https://issues.apache.org/jira/browse/SLING-5407
